# Generated by Django 4.2.7 on 2023-11-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Bills', 'Bills'), ('Online shopping', 'Online shopping'), ('Clothing', 'Clothing'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('Miscellaneous', 'Miscellaneous')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='tracker.budget'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='tracker.category'),
        ),
    ]
