# Generated by Django 4.2.7 on 2023-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_expense_budget_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Groceries', 'Groceries'), ('Bills', 'Bills'), ('Online shopping', 'Online shopping'), ('Clothing', 'Clothing'), ('Transport', 'Transport'), ('Utilities', 'Utilities'), ('Miscellaneous', 'Miscellaneous')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='budget',
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='budget',
        ),
    ]
