# Generated by Django 4.2.7 on 2023-11-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_alter_expense_category_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
