# Generated by Django 4.2.7 on 2023-11-25 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_expense_user_alter_expensecategory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
