# Generated by Django 4.2.7 on 2023-11-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
