# Generated by Django 4.2.7 on 2023-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_remove_expense_created_at_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='user',
        ),
    ]
