# Generated by Django 4.2.7 on 2023-11-25 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_remove_expensecategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseCategory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
