# Generated by Django 4.2.7 on 2023-11-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_rename_expensecategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Transport', 'Transport'), ('Bills', 'Bills'), ('Others', 'Others')], default=None),
        ),
    ]
